# Generated by Django 3.2.3 on 2025-01-02 16:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('0.0'), 'Баланс не может быть ниже 0.0.')], verbose_name='Баланс')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], editable=False, max_length=8, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('1.0'), 'Сумма не может быть ниже 1.0.')], verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время операции')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.wallet', verbose_name='Кошелёк')),
            ],
        ),
    ]
